### ISSUE TITLE
Example Page no longer exists

### ISSUE THREAD

**Issue by zarif3624** [fastily/jwiki#10]
The example page where you say to make edits does not exist. The structure of the project has changed since you created it. I'm not certain on how to use this project as there is not a particular file to write code in. Could you please offer some assistance with this? Thanks.

**Comment by zarif3624** [comment]
JwikiExample.java is the file I am referring to. It is no longer in the directory stated.

**Comment by zarif3624** [comment]
Mistake on my part, sorry

**Comment by boris-github** [comment]
@zarif3624 where can we find the refered JwikiExample.java? It's been removed.

**Comment by fastily** [comment]
Hi @boris-github, did you clone this repository: [fastily/jwiki-starter](https://github.com/fastily/jwiki-starter)?

**Comment by boris-github** [comment]
@fastily I didn't. I didn't realise it was asking to clone a different repo (I overlooked it).
My suggestion to prevent this misunderstandgings in the future would be linking `JwikiExample.java` in the second step to the class location in the jwiki-starter repo:

[JwikiExample.java](https://github.com/fastily/jwiki-starter/blob/master/src/main/java/jwikistarter/JwikiExample.java)

I personally don't think that cloning a repo is the right way of informing developers how to use the library. Instead a simple link would present a user with a fast access how to start using the `Wiki` class.
