### ISSUE TITLE
Retrieving multiple page contents in one mediawiki API call

### ISSUE THREAD

**Issue by benjaminkomen** [fastily/jwiki#12]
Hello,

I tried out this library today for my github project [TibiaWikiApi](https://github.com/benjaminkomen/TibiaWikiApi). I am exploring to use your library, but currently I'm using [jwbf](https://github.com/eldur/jwbf).
I want to do the following thing:
1. Get a list of titles in a category, this is no problem with your wiki.getCategoryMembers() method.
2. Get all those pages individually.

For this second step I did not find an efficient method yet. Of course it is possible to do multiple subsequent calls to the wiki api using your wiki.getPageText() for every page title, but I would like to do this more efficiently. In the mediawiki API this is possible, e.g.: 
https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=jsonfm&formatversion=2&titles=Foo|Bar|Cat
All page titles are listed in the titles parameter, separated by a pipe. The only limit is how much characters fit in an url, before it gets too long. As this results in less api calls, this method is a lot faster.

What method from this library can be used to achieve this? If this is not possible yet, I can make an attempt to build this myself and offer a pull request.

**Comment by fastily** [comment]
Hi @benjaminkomen,

Have you tried out MQuery's [getPageText()](https://fastily.github.io/jwiki/docs/jwiki/fastily/jwiki/core/MQuery.html#getPageText-fastily.jwiki.core.Wiki-java.util.Collection-) method?

Something like 

```java
Wiki wiki = new Wiki("en.wikipedia.org");
System.out.println( MQuery.getPageText(wiki, wiki.getCategoryMembers("YOUR_CATEGORY_HERE")) );
```

ought to do the trick.

**Comment by benjaminkomen** [comment]
Thanks fastily! This definitely works like I want it to do. I had not seen the class MQuery yet. I think it would be a good thing to give some more exposure to it on your [examples wiki page](https://github.com/fastily/jwiki/wiki/Examples). What do you think? I could write something up if you want.

**Comment by fastily** [comment]
Sure, I have added an `MQuery.getPageText()` example to the Wiki.

However, I've deliberately avoided adding too many `MQuery` examples since the majority of query methods in `Wiki.java` are backed by a call to `MQuery` anyways.

**Comment by benjaminkomen** [comment]
Thanks!
