### ISSUE TITLE
URL to wiki domain assumes format which is not general enough

### ISSUE THREAD

**Issue by benjaminkomen** [fastily/jwiki#13]
In the Wiki class you provide a String called 'domain' as input to the constructor. It is used in a constructor to construct an URL in the following format: https://%s/w/api.php

Although this is correct for Wikipedia, it is not how it works for Wikia wikis (like [the one](http://tibia.wikia.com/api.php) I use). There the format is: https://%s/api.php, so without the slash w.

My 'work-around' is to use the following constructor: 
`wiki = new Wiki(null, null, HttpUrl.parse("https://tibia.wikia.com/api.php"), null, null)`

But it would be nice if there was a more user-friendly way, or some explanation in the documentation that you have to take care for this if you're not using Wikipedia but another wiki.

**Comment by fastily** [comment]
Hi @benjaminkomen.  I updated the docs in c74eb3ef633f45201402291209c6feec6ae10596; this revision will go live with the next release of jwiki.

**Comment by benjaminkomen** [comment]
Thanks, looks good!
