### ISSUE TITLE
Code style: using interfaces instead of implementation

### ISSUE THREAD

**Issue by benjaminkomen** [fastily/jwiki#14]
In my opinion ([and in the opinion of other Java developers](https://stackoverflow.com/questions/147468/why-should-the-interface-for-a-java-class-be-preferred)) it would be better to let the methods of this API return collection interfaces instead of their implementation. So for example in the [Wiki](https://fastily.github.io/jwiki/docs/jwiki/fastily/jwiki/core/Wiki.html) class you will see a lot of methods which return `ArrayList<String>` where it would be beter to return `List<String>`. The same goes for Map instead of HashMap and so forth.

What do you think @fastily ? It could be that I am overlooking some design consideration, in which case I would love you to enlighten me.

This issue is intended as constructive criticism, not merely bashing on you ;)

**Comment by fastily** [comment]
Hi @benjaminkomen.  Good suggestion, but it's not possible to change without causing breakage for my users who have been with jwiki since the 1.0 release.   Might be good to consider for the 2.0 release when/if it ever happens.

**Comment by benjaminkomen** [comment]
Yes, this is a breaking change indeed. We can close this issue, but add a version 2.0 milestone or something and reopen it at some point in the future.
