### ISSUE TITLE
Retrieve image list from given page

### ISSUE THREAD

**Issue by renankcb** [fastily/jwiki#18]
Current method MQuery.getImageInfo return  an empty image array, but there are content on the page.
API was updated to use "generator" parameter

https://stackoverflow.com/questions/36972156/how-to-search-images-in-wikimedia-commons-by-api

**Comment by fastily** [comment]
Hi @renankcb,

Could you please provide examples, code snippets, and descriptions of what you are trying to accomplish? 

Thanks!

**Comment by fastily** [comment]
Closing per inactivity; feel free to reopen if you're still experiencing issues.
