### ISSUE TITLE
VisualEditor Preview API

### ISSUE THREAD

**Issue by don-vip** [fastily/jwiki#20]
Can you please add new methods to interact with the VisualEditor API?
I didn't find a documentation (but didn't look for it long). 
I am in particular interested by what happens when we click the Preview button from VisualEditor. It allows to preview any WikiCode sent to it by returning the corresponding HTML code.

Here is the client code of the VisualEditor extension:
https://github.com/wikimedia/mediawiki-extensions-VisualEditor/blob/ef25e831b99471bde1510d925d8fcc46da115e54/modules/ve-mw/init/ve.init.mw.ArticleTarget.js#L964

Here is the API server code:
https://github.com/wikimedia/mediawiki-extensions-VisualEditor/blob/ef25e831b99471bde1510d925d8fcc46da115e54/includes/ApiVisualEditor.php#L224

**Comment by fastily** [comment]
Hi don-vip,

Can you share your specific use case? 

If you want just HTML, you can use the [wikitext to html transform](https://en.wikipedia.org/api/rest_v1/#/Transforms/post_transform_wikitext_to_html) in the RESTBase API.

**Comment by don-vip** [comment]
It's exactly my use case, but I didn't know this API! Is it available on Wikimedia Commons? https://commons.wikipedia.org/api/rest_v1/ does not work. 

My use case is I am coding an import tool to Commons. I want to preview the Wiki code I generate as it will be displayed on Commons (so, with template resolution and so on). I can't use the English Wikipedia instance for that. My current code is here:
https://phabricator.wikimedia.org/source/tool-spacemedia/browse/master/src/main/java/org/wikimedia/commons/donvip/spacemedia/service/CommonsService.java$149

**Comment by fastily** [comment]
The Commons RESTBase API is available at https://commons.wikimedia.org/api/rest_v1/

**Comment by don-vip** [comment]
Oh, I see my stupid mistake  :) Thank you, it solves my use case.
