### ISSUE TITLE
Filter to get contributions that are new pages only

### ISSUE THREAD

**Issue by xbony2** [fastily/jwiki#22]
I don't know if this is possible with the mediawiki api but on Special:Contributions, I can filter it by pressing the button with the label "Only show edits that are page creations." For my bot I'm basically looking through every contribution which is very taxing (lol i crashed the wiki multiple times, "429 Too Many Requests"), so if it can be filtered just through the API, that would be a very good thing.

**Comment by fastily** [comment]
Hi @xbony2, I believe this is possible.  I'll play around with it and post an update within the next few days.

**Comment by xbony2** [comment]
Awesome, glad to hear ^_^
