### ISSUE TITLE
Add http version of Builder.withDomain()

### ISSUE THREAD

**Issue by seongwon-kang** [fastily/jwiki#26]
https://github.com/fastily/jwiki/blob/be558c3ed58b4d2f6f7487aec6702d4053519770/src/main/java/org/fastily/jwiki/core/Wiki.java#L120

if I call `Wiki.Builder().withDomain()`, format string will set domain name with https.
but my private test wiki is not configured with https, and there is no way to set http url with builder conviniently, and if I call `withDomain()`, It will cause a `NullPointerException` because there is no https url for private wiki.

**Comment by fastily** [comment]
Hi @seongwon-kang:

`Wiki.Builder.withApiEndpoint()` does what you're asking for.  

For example:
```java
new Wiki.Builder().withApiEndpoint(HttpUrl.parse("http://YOUR_HOSTNAME/w/api.php")).build();
```

**Comment by fastily** [comment]
Closing per inactivity, and because desired functionality already exists
