### ISSUE TITLE
Creating a non-continuing MQuery with a specified limit

### ISSUE THREAD

**Issue by NicolasWinsten** [fastily/jwiki#29]
Hello,

jwiki has helped me out a lot, since I'm a beginner programmer and very uncomfortable with MediaWiki.

I'm having trouble figuring out how to create a terminating query that stops making requests once its received a certain number of items.  For example, whatLinksHere("United States") will take forever, since MediaWiki will only return 500 items at a time per request as far as I know.

I want to be able to make a query that terminates just after a few requests to MediaWiki and returns whatever's been received.  Is there a good way to do this?

Thank you!

**Comment by fastily** [comment]
Hi @NicolasWinsten,

Glad to hear you're finding jwiki useful!

Unfortunately this is a current limitation of jwiki, and there's no clean way to do it without rearchitecting significant portions of the library.

I'm planning to include this functionality in the future, but not before the v2.0 release.  I haven't had much time to work on jwiki lately, but hopefully I will sometime in the next few months.

**Comment by NicolasWinsten** [comment]
Thanks for your reply!
