### ISSUE TITLE
idea to make contributions easier

### ISSUE THREAD

**Issue by seinecle** [fastily/jwiki#33]
Hi,
Thank you for a really useful library. I would need to add a "fetch all pages of a given category" feature, so I looked at the code to see how I could contribute.
My first impression is that even if this is trivial, some naming conventions could change to help contributors find their way. NS, FS, etc... could be spelled out in longer names?
I forked the repo and I am making these changes for my convenience. Would you accept a pull request in this sense?

**Comment by seinecle** [comment]
I just submitted a related push request: https://github.com/fastily/jwiki/pull/34

**Comment by fastily** [comment]
Hi @seinecle,

>  "fetch all pages of a given category" feature

I think you may be looking for [Wiki.getCategoryMembers()](https://fastily.github.io/jwiki/docs/jwiki/org/fastily/jwiki/core/Wiki.html#getCategoryMembers(java.lang.String,org.fastily.jwiki.core.NS...))

> Would you accept a pull request in this sense?

Just commented on the PR :)

**Comment by fastily** [comment]
[housekeeping] marking closed per discussion
