### ISSUE TITLE
GPL with classpath exception

### ISSUE THREAD

**Issue by trueg** [fastily/jwiki#38]
Is there a chance you could include a classpath exception to your licencing? That way we could use this fine lib in internal products without the legal department screaming at us. ;)

**Comment by fastily** [comment]
Hi @trueg,

Sorry, I'm not interested in adding a classpath exception.

However, I'll be happy to offer your company a license to use the library (without the restrictions imposed by the GPL) in exchange for a donation to the project.

If interested, please get in touch: `"fastily" + "@" + "fastily.org"`

Thanks!

**Comment by trueg** [comment]
Thanks for the quick reply. Totally understandable. I will see if I can make that happen but please do not hold your breath, it is a BIG company and stuff like that can take ages. :/
