### ISSUE TITLE
method wiki.basicGET

### ISSUE THREAD

**Issue by hannahceline** [fastily/jwiki#39]
Hi,

could you provide an example for the method wiki.basicGET please? That would be awesome! I tried to use it, however I only got empty responses.

**Comment by fastily** [comment]
hi @hannahceline ,

I'm planning to deprecate the basicGET method in a future release of jwiki.  May I ask what your use case is?

**Comment by fastily** [comment]
Housekeeping, closing per inactivity.  Feel free to reopen if anything new comes up.
