### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by Stallin0** [fastily/jwiki#41]
trying to start Wiki wiki = new Wiki.Builder().build(); causes the issue "Caused by: java.lang.NullPointerException: Attempt to read from field 'com.google.gson.JsonObject io.github.fastily.jwiki.core.WQuery$QReply.input' on a null object reference"  

this code should work with android correct?

![Screenshot 2022-06-13 231135](https://user-images.githubusercontent.com/66690807/173485638-71334374-de9b-4fb9-a2c6-c63a822b4ec6.png)

**Comment by fastily** [comment]
Hi @Stallin0,

jwiki was not designed specifically with Android in mind, although to my knowledge there's nothing that would prevent it from being compatible.

Can you verify that you are using a minimum of Java 11 and that your Android application has the permissions necessary to access the internet?

Also, could you also please provide some code and/or a sample project that reproduces this behavior?

**Comment by fastily** [comment]
closing as unable to reproduce, and per inactivity; feel free to re-open if the issue is still occurring
