### ISSUE TITLE
Add support for skipping some cookies from saving in JwikiCookieJar 

### ISSUE THREAD

**Issue by kb0** [fastily/jwiki#42]
JwikiCookieJar save all new cookies without any filtering, but after each page edit - there is a new cookie like "mediawikiPostEditRevision98996=saved" (MediaWiki send post-edit cookie indicating the user just saved a particular revision). 

After several calls of wiki.edit() - there are a lot of cookies "mediawikiPostEditRevision<revision id>=saved" in each new http-request, so web server start to return - "400 Bad Request - request header or cookie too large".

it would be great if JwikiCookieJar skip such cookies from saving

**Comment by fastily** [comment]
Hi @kb0,

I'm not able to reproduce.  Could you please share some sample code that demonstrates this bug?

**Comment by kb0** [comment]
I'm not able reproduce it on pure MediaWiki installation, but it's "works" on MediaWiki + PageForms (at least mediawiki 1.31 + pageforms 4.5.1)

https://github.com/kb0/fastily-jwiki-issues-42 - sample with MediaWiki docker container (1.31 + PageForms)
Errors starts at ~227 - ERROR: [Mediawiki @ localhost]: Could not edit 'Page 227', aborting.

**Comment by fastily** [comment]
Thanks!  I just pushed a commit to master that may address this issue.  Could you please try it out and let me know if it works for you?

**Comment by kb0** [comment]
No, the same problem. It's possible to filter out such cookies using CookiePolicy.shouldAccept:
```
    JavaNetCookieJar(CookieManager(null, object : CookiePolicy {
        override fun shouldAccept(uri: URI, cookie: HttpCookie): Boolean {
            if (cookie.name.startsWith("mediawikiPostEditRevision")) {
                return false;
            }

            return true;
        }
    }))
```
May be make optional pass of CookieJar/CookiePolicy through Wiki.Builder()

**Comment by fastily** [comment]
Ah, that's unfortunate.  I did a quick search on Wikimedia Phabricator and this is apparently a known issue: [T69790](https://phabricator.wikimedia.org/T69790), [T112771](https://phabricator.wikimedia.org/T112771), [T211233](https://phabricator.wikimedia.org/T211233).

> May be make optional pass of CookieJar/CookiePolicy through Wiki.Builder()

Good suggestion, I'll do this
