### ISSUE TITLE
Getting the url of a page

### ISSUE THREAD

**Issue by OneByteGH** [fastily/jwiki#43]
How do I get the url of that page, I went through the docs multiple times but still didn't find any method to get the url. Kindly lmk if theres one

**Comment by fastily** [comment]
Hi @OneByteGH.

Why do you need the API and/or jwiki to do this for you?  Using the base URL of the wiki you're targeting and the page title, you can derive the URL with something like

```java
System.out.println("https://en.wikipedia.org/wiki/" + URLEncoder.encode("The Avengers (2012 film)", StandardCharsets.UTF_8));
// prints "https://en.wikipedia.org/wiki/The_Avengers_(2012_film)"
```

**Comment by OneByteGH** [comment]
Ooh, thank you so much, didnt think of that
