### ISSUE TITLE
Loggin Error when trying to use fandom as a builder

### ISSUE THREAD

**Issue by AngelFireLA** [fastily/jwiki#45]
I managed to use fandom as my builder, I can get all the info and stuff
But when I try to login, it fails.
I tried :
- real username and pass
- creating a bot account
- using the 2 username/password that are given with a bot account
Here is the log :
INFO: [32m[<Anonymous> @ laboulangerie.fandom.com]: Try login for CroissantBot@CroissantBot[0m
false

Here is my simple test code (with username and password hidden) :
```
public class App {
    public static void main( String[] args ){
    	Wiki wiki = new Wiki.Builder().withDomain("laboulangerie.fandom.com/fr/api.php").build();
    	System.out.println(wiki.login("myusername", "mypassword"));
    }
}
```

**Comment by fastily** [comment]
Hi @AngelFireLA,

You'll want to use the [.withApiEndpoint()](https://www.javadoc.io/doc/io.github.fastily/jwiki/latest/io/github/fastily/jwiki/core/Wiki.Builder.html) method instead of `.withDomain()`.

So in your case, the complete line will probably look something like
```java
Wiki wiki = new Wiki.Builder().withApiEndpoint(HttpUrl.parse("https://laboulangerie.fandom.com/fr/api.php")).build();
```

**Comment by AngelFireLA** [comment]
thank you it worked !
