### ISSUE TITLE
Crash when trying to create wiki object with Wiki.Builder().build()

### ISSUE THREAD

**Issue by eyal4D** [fastily/jwiki#46]
NOTE: I am trying to run this code as part of an android app using android studio and gradle.
I also noticed someone opened an issue about this problem in the past but no solution was found.

This is my code:
```
import io.github.fastily.jwiki.core.*;
import io.github.fastily.jwiki.dwrap.*;
import okhttp3.HttpUrl;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Wiki wiki = new Wiki.Builder().build();
    }
}
```
When creating the wiki object the program crashes with the error being:
`"java.lang.NullPointerException: Attempt to read from field 'com.google.gson.JsonObject io.github.fastily.jwiki.core.WQuery$QReply.input' on a null object reference in method 'void io.github.fastily.jwiki.core.Wiki.refreshNS()'"`

**Comment by fastily** [comment]
Hi @eyal4D,

Can you confirm that your Android app has the necessary permissions to access the internet?  

Assuming this is related to #41

Also noting for the record that `jwiki` wasn't designed with Android in mind, so if you have a plain Java program (i.e. without Android) that reproduces this behavior that would be helpful.

**Comment by fastily** [comment]
closing as unable to reproduce, and per inactivity; feel free to re-open if the issue is still occurring
