### ISSUE TITLE
Request to make the logging optional

### ISSUE THREAD

**Issue by OpSimple** [fastily/jwiki#9]
Hi,

I'd like to thank you for this great and damn easy wiki api. And, it really works cool! It logs for every call, its great! But, I want to get rid of the logs while its being used in an application. And, I can't turn it off cause there's no way. Can you please add a feature to disable the logging when unneeded?
Thank you!

Regards

**Comment by fastily** [comment]
Hi @OpSimple ,

Thanks for the feedback!

Good suggestion, I'll get that into the next release.
